version: '3.1'

services:

  mysql:
    image: mysql:5.7.35
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    container_name: mysql
    dns:
      - 119.29.29.29
      - 114.114.114.114
      - 8.8.8.8
    networks:
      default:
        ipv4_address: 172.18.0.2
    ports:
      - "13306:3306"
    volumes:
      - F:\workspace\docker\1\jiuzhou\mysql\config:/etc/mysql/conf.d
      - F:\workspace\docker\1\jiuzhou\mysql\data:/var/lib/mysql
      - F:\workspace\docker\1\jiuzhou\mysql\initsql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'yuebaix'
      TZ: Asia/Shanghai

  zk:
    image: zookeeper:3.7.0
    restart: always
    container_name: zk
    hostname: zk
    dns:
      - 119.29.29.29
      - 114.114.114.114
      - 8.8.8.8
    networks:
      default:
        ipv4_address: 172.18.0.8
    ports:
      - "12181:2181"
#      - "11001:8080"
    volumes:
      - F:\workspace\docker\1\jiuzhou\zk\data:/data
      - F:\workspace\docker\1\jiuzhou\zk\datalog:/datalog
      - F:\workspace\docker\1\jiuzhou\zk\logs:/logs
    environment:
      ZOO_STANDALONE_ENABLED: 'true'
      ZOO_ADMINSERVER_ENABLED: 'false'


networks:
  default:
    external:
      name: inner-network