version: '3.1'

services:

  mysql:
    image: mysql:5.7.35
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    container_name: mysql
    dns:
      - 119.29.29.29
      - 114.114.114.114
      - 8.8.8.8
    networks:
      default:
        ipv4_address: 172.18.0.2
    ports:
      - "13306:3306"
    volumes:
      - E:\jiuzhou\volumes\mysql\config:/etc/mysql/conf.d
      - E:\jiuzhou\volumes\mysql\data:/var/lib/mysql
      - E:\jiuzhou\volumes\mysql\initsql:/docker-entrypoint-initdb.d
    environment:
#      MYSQL_ROOT_PASSWORD: 'yuebaix'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: Asia/Shanghai

  zk:
    image: zookeeper:3.7.0
    restart: always
    container_name: zk
    hostname: zk
    dns:
      - 119.29.29.29
      - 114.114.114.114
      - 8.8.8.8
    networks:
      default:
        ipv4_address: 172.18.0.11
    ports:
      - "12181:2181"
#      - "11011:8080"
    volumes:
      - E:\jiuzhou\volumes\zk\data:/data
      - E:\jiuzhou\volumes\zk\datalog:/datalog
      - E:\jiuzhou\volumes\zk\logs:/logs
    environment:
      ZOO_STANDALONE_ENABLED: 'true'
      ZOO_ADMINSERVER_ENABLED: 'false'

  apollo-quick-start:
    image: yuebaix/apollo-quick-start
    restart: always
    container_name: apollo-quick-start
    dns:
      - 119.29.29.29
      - 114.114.114.114
      - 8.8.8.8
    networks:
      default:
        ipv4_address: 172.18.0.21
    depends_on:
      - mysql
    ports:
      - "11021:8080"
      - "11022:8090"
      - "11023:8070"
    environment:
      JAVA_OPTS: '-Xms100m -Xmx1000m -Xmn100m -Xss256k -XX:MetaspaceSize=10m -XX:MaxMetaspaceSize=250m'
    links:
      - mysql:apollo-db


networks:
  default:
    external:
      name: inner-network