spring:
  cloud:
    gateway:
      routes:
        - id: route-app-bizagg
          uri: lb://app-bizagg
          predicates:
            - Path=/app-bizagg/**
          filters:
            - AddRequestHeader=Authorization, Basic eXVlYmFpeDp5dWViYWl4
        - id: route-app-biz
          uri: lb://app-biz
          predicates:
            - Path=/app-biz/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=Authorization, Basic eXVlYmFpeDp5dWViYWl4
